version: "3.3"

services:
  users-db:
    container_name: users-db
    build:
    - context: ./services/users/project/db
    - dockerfile: Dockerfile
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root321

  user-service:
    container_name: user-service
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - "5000"
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=mysql+pymysql://root:root321@users-db:3306/users_prod
      - DATABASE_TEST_URL=mysql+pymysql://root:root321@users-db:3306/users_test
    depends_on:
      - users-db
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 manage:app

  nginx:
    container_name: nginx
    build: ./services/nginx/
    restart: always
    ports:
      - 8080:80
    depends_on:
      - user-service
    links:
      - user-service
