FROM node:9.4

MAINTAINER 'zhaofqwoo@gmail.com'

# 设置工作目录
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ADD package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.0.17 -g --slient

CMD ["npm", "start"]